"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var require_auth_1 = require("../middleware/require-auth");
var express_1 = require("express");
var pantry_1 = require("../controllers/pantry");
var router = (0, express_1.Router)();
var prefix = '/household/:householdId/pantry';
router.get(prefix, pantry_1.getPantries);
router.post("".concat(prefix, "/:pantryId"), pantry_1.upsertPantryItem);
router.get("".concat(prefix, "/:pantryId/items"), (0, require_auth_1.default)(), pantry_1.getAllPantryItems);
router.get("".concat(prefix, "/:pantryId/items/:itemId"), (0, require_auth_1.default)(), pantry_1.getPantryItem);
router.get("".concat(prefix, "/:pantryId/categories"), (0, require_auth_1.default)(), pantry_1.getPantryCategories);
exports.default = router;
