// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const FoodExpirationData: any[] = [
    {
        category: 'Salad',
        freezerDays: null,
        fridgeDays: 4,
        name: 'Egg, chicken, ham, tuna, and macaroni salads',
    },
    { category: 'Hot dogs', freezerDays: 45, fridgeDays: 7, name: 'Hot dogs (opened)' },
    { category: 'Hot dogs', freezerDays: 45, fridgeDays: 14, name: 'Hot dogs (unopened)' },
    {
        category: 'Luncheon meat',
        freezerDays: 45,
        fridgeDays: 5,
        name: 'Luncheon meat (opened or deli sliced)',
    },
    {
        category: 'Luncheon meat',
        freezerDays: 45,
        fridgeDays: 14,
        name: 'Luncheon meat (unopened)',
    },
    { category: 'Bacon and sausage', freezerDays: 30, fridgeDays: 7, name: 'Bacon' },
    { category: 'Bacon and sausage', freezerDays: 45, fridgeDays: 2, name: 'Sausage (raw)' },
    {
        category: 'Bacon and sausage',
        freezerDays: 45,
        fridgeDays: 7,
        name: 'Sausage (fully cooked)',
    },
    {
        category: 'Ground meats',
        freezerDays: 105,
        fridgeDays: 2,
        name: 'Ground meats (beef, poultry, etc.)',
    },
    { category: 'Fresh meat', freezerDays: 270, fridgeDays: 5, name: 'Steaks' },
    { category: 'Fresh meat', freezerDays: 270, fridgeDays: 5, name: 'Chops' },
    { category: 'Fresh meat', freezerDays: 270, fridgeDays: 5, name: 'Roasts' },
    { category: 'Ham', freezerDays: 180, fridgeDays: 5, name: 'Ham (fresh, uncured, uncooked)' },
    { category: 'Ham', freezerDays: 105, fridgeDays: 4, name: 'Ham (fresh, uncured, cooked)' },
    {
        category: 'Ham',
        freezerDays: 105,
        fridgeDays: 7,
        name: 'Ham (cured, cook-before-eating, uncooked)',
    },
    {
        category: 'Ham',
        freezerDays: 45,
        fridgeDays: 14,
        name: 'Ham (fully-cooked, vacuum-sealed, unopened)',
    },
    {
        category: 'Ham',
        freezerDays: 45,
        fridgeDays: 5,
        name: 'Ham (cooked, store-wrapped, slices or spiral)',
    },
    { category: 'Ham', freezerDays: 30, fridgeDays: 7, name: 'Ham (country, cooked)' },
    {
        category: 'Ham',
        freezerDays: null,
        fridgeDays: 225,
        name: 'Ham (canned, keep refrigerated)',
    },
    { category: 'Ham', freezerDays: 45, fridgeDays: 4, name: 'Ham (canned, shelf-stable, opened)' },
    { category: 'Ham', freezerDays: 30, fridgeDays: 75, name: 'Prosciutto or Serrano ham (cut)' },
    { category: 'Poultry', freezerDays: 365, fridgeDays: 2, name: 'Chicken or turkey (whole)' },
    { category: 'Poultry', freezerDays: 270, fridgeDays: 2, name: 'Chicken or turkey (pieces)' },
    {
        category: 'Fish',
        freezerDays: 75,
        fridgeDays: 2,
        name: 'Fatty fish (salmon, mackerel, tuna, etc.)',
    },
    { category: 'Fish', freezerDays: 180, fridgeDays: 2, name: 'Lean fish (cod, haddock, etc.)' },
    { category: 'Shellfish', freezerDays: 90, fridgeDays: 3, name: 'Fresh crab meat' },
    { category: 'Shellfish', freezerDays: 90, fridgeDays: 3, name: 'Fresh lobster' },
    { category: 'Shellfish', freezerDays: null, fridgeDays: 1, name: 'Live crab/lobster' },
    {
        category: 'Shellfish',
        freezerDays: null,
        fridgeDays: 7,
        name: 'Live clams, mussels, oysters, scallops',
    },
    { category: 'Shellfish', freezerDays: 360, fridgeDays: 4, name: 'Shrimp or crayfish' },
    {
        category: 'Shellfish',
        freezerDays: 105,
        fridgeDays: 7,
        name: 'Shucked clams/mussels/oysters/scallops',
    },
    { category: 'Shellfish', freezerDays: 360, fridgeDays: 2, name: 'Squid' },
    { category: 'Eggs', freezerDays: null, fridgeDays: 28, name: 'Raw eggs in shell' },
    { category: 'Eggs', freezerDays: 365, fridgeDays: 3, name: 'Raw egg whites or yolks' },
    { category: 'Eggs', freezerDays: null, fridgeDays: 7, name: 'Hard-cooked eggs' },
    {
        category: 'Eggs',
        freezerDays: null,
        fridgeDays: 7,
        name: 'Egg substitutes (liquid, unopened)',
    },
    {
        category: 'Eggs',
        freezerDays: null,
        fridgeDays: 3,
        name: 'Egg substitutes (liquid, opened)',
    },
    {
        category: 'Eggs',
        freezerDays: 365,
        fridgeDays: 7,
        name: 'Egg substitutes (frozen, unopened)',
    },
    {
        category: 'Eggs',
        freezerDays: null,
        fridgeDays: 4,
        name: 'Egg substitutes (frozen, opened)',
    },
    { category: 'Casseroles', freezerDays: 75, fridgeDays: 4, name: 'Casseroles with eggs' },
    { category: 'Eggnog', freezerDays: 180, fridgeDays: 4, name: 'Eggnog (commercial)' },
    { category: 'Eggnog', freezerDays: null, fridgeDays: 3, name: 'Eggnog (homemade)' },
    { category: 'Pies', freezerDays: 45, fridgeDays: 4, name: 'Pie (pumpkin or pecan)' },
    { category: 'Pies', freezerDays: null, fridgeDays: 4, name: 'Pie (custard or chiffon)' },
    { category: 'Quiche', freezerDays: 75, fridgeDays: 5, name: 'Quiche with filling' },
    { category: 'Soups', freezerDays: 75, fridgeDays: 4, name: 'Soups and stews' },
    {
        category: 'Leftovers',
        freezerDays: 120,
        fridgeDays: 4,
        name: 'Cooked meat or poultry leftovers',
    },
    { category: 'Leftovers', freezerDays: 60, fridgeDays: 4, name: 'Chicken nuggets or patties' },
    { category: 'Leftovers', freezerDays: 45, fridgeDays: 4, name: 'Pizza' },
    {
        category: 'Dry goods',
        freezerDays: 730,
        fridgeDays: 365,
        name: 'Flour (all-purpose)',
        pantryDays: 180,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Sugar (white, granulated)',
        pantryDays: 1825,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Brown sugar',
        pantryDays: 720,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Powdered sugar',
        pantryDays: 720,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Rice (white, uncooked)',
        pantryDays: 1825,
    },
    {
        category: 'Dry goods',
        freezerDays: 730,
        fridgeDays: 365,
        name: 'Rice (brown, uncooked)',
        pantryDays: 180,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Pasta (dry, uncooked)',
        pantryDays: 720,
    },
    { category: 'Dry goods', freezerDays: 730, fridgeDays: 730, name: 'Oats', pantryDays: 365 },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Cereal (unopened)',
        pantryDays: 365,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Cereal (opened)',
        pantryDays: 60,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Beans (dried, uncooked)',
        pantryDays: 730,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Lentils',
        pantryDays: 730,
    },
    {
        category: 'Bakery',
        freezerDays: 90,
        fridgeDays: 14,
        name: 'Bread (store-bought, sliced)',
        pantryDays: 7,
    },
    { category: 'Bakery', freezerDays: 90, fridgeDays: 7, name: 'Bread (homemade)', pantryDays: 3 },
    {
        category: 'Dry goods',
        freezerDays: 730,
        fridgeDays: 180,
        name: 'Coffee beans (whole)',
        pantryDays: 180,
    },
    {
        category: 'Dry goods',
        freezerDays: 730,
        fridgeDays: 180,
        name: 'Coffee (ground)',
        pantryDays: 90,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Tea (loose or bagged)',
        pantryDays: 730,
    },
    {
        category: 'Pantry staples',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Peanut butter',
        pantryDays: 180,
    },
    {
        category: 'Pantry staples',
        freezerDays: null,
        fridgeDays: null,
        name: 'Cooking oil (vegetable, canola)',
        pantryDays: 365,
    },
    {
        category: 'Pantry staples',
        freezerDays: null,
        fridgeDays: null,
        name: 'Olive oil',
        pantryDays: 730,
    },
    {
        category: 'Pantry staples',
        freezerDays: null,
        fridgeDays: null,
        name: 'Honey',
        pantryDays: 1825,
    },
    { category: 'Dry goods', freezerDays: null, fridgeDays: null, name: 'Salt', pantryDays: 3650 },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Pepper (ground)',
        pantryDays: 1095,
    },
    {
        category: 'Dry goods',
        freezerDays: null,
        fridgeDays: null,
        name: 'Spices and herbs (dried)',
        pantryDays: 730,
    },

    { category: 'Fruit', freezerDays: 365, fridgeDays: 60, name: 'Apples', pantryDays: 14 },
    { category: 'Fruit', freezerDays: 90, fridgeDays: 10, name: 'Bananas', pantryDays: 7 },
    { category: 'Fruit', freezerDays: 90, fridgeDays: 30, name: 'Oranges', pantryDays: 14 },
    { category: 'Fruit', freezerDays: 120, fridgeDays: 30, name: 'Lemons', pantryDays: 14 },
    { category: 'Fruit', freezerDays: 120, fridgeDays: 30, name: 'Limes', pantryDays: 14 },
    { category: 'Fruit', freezerDays: 365, fridgeDays: 14, name: 'Grapes', pantryDays: 2 },
    {
        category: 'Fruit',
        freezerDays: 365,
        fridgeDays: 7,
        name: 'Berries (strawberries, raspberries, etc.)',
        pantryDays: 1,
    },
    { category: 'Fruit', freezerDays: 60, fridgeDays: 10, name: 'Melons (whole)', pantryDays: 7 },
    { category: 'Fruit', freezerDays: 60, fridgeDays: 5, name: 'Melons (cut)', pantryDays: null },
    { category: 'Fruit', freezerDays: 60, fridgeDays: 10, name: 'Avocados', pantryDays: 7 },
    { category: 'Vegetable', freezerDays: 120, fridgeDays: 14, name: 'Tomatoes', pantryDays: 7 },
    {
        category: 'Vegetable',
        freezerDays: null,
        fridgeDays: null,
        name: 'Potatoes (white, russet)',
        pantryDays: 60,
    },
    {
        category: 'Vegetable',
        freezerDays: null,
        fridgeDays: null,
        name: 'Sweet potatoes',
        pantryDays: 60,
    },
    {
        category: 'Vegetable',
        freezerDays: 365,
        fridgeDays: 90,
        name: 'Onions (whole)',
        pantryDays: 30,
    },
    {
        category: 'Vegetable',
        freezerDays: 365,
        fridgeDays: 120,
        name: 'Garlic (whole heads)',
        pantryDays: 90,
    },
    { category: 'Vegetable', freezerDays: 365, fridgeDays: 30, name: 'Carrots', pantryDays: 7 },
    { category: 'Vegetable', freezerDays: 120, fridgeDays: 21, name: 'Celery', pantryDays: null },
    {
        category: 'Vegetable',
        freezerDays: 120,
        fridgeDays: 14,
        name: 'Bell peppers',
        pantryDays: 3,
    },
    { category: 'Vegetable', freezerDays: null, fridgeDays: 7, name: 'Lettuce', pantryDays: null },
    { category: 'Vegetable', freezerDays: 365, fridgeDays: 5, name: 'Spinach', pantryDays: null },
    { category: 'Vegetable', freezerDays: 365, fridgeDays: 7, name: 'Broccoli', pantryDays: null },
    {
        category: 'Vegetable',
        freezerDays: 365,
        fridgeDays: 7,
        name: 'Cauliflower',
        pantryDays: null,
    },
    { category: 'Vegetable', freezerDays: 90, fridgeDays: 7, name: 'Zucchini', pantryDays: null },
    { category: 'Vegetable', freezerDays: null, fridgeDays: 10, name: 'Cucumbers', pantryDays: 5 },
    { category: 'Vegetable', freezerDays: 120, fridgeDays: 7, name: 'Mushrooms', pantryDays: null },
    {
        category: 'Vegetable',
        freezerDays: 365,
        fridgeDays: 3,
        name: 'Corn (fresh, in husk)',
        pantryDays: 1,
    },
    {
        category: 'Vegetable',
        freezerDays: 365,
        fridgeDays: 7,
        name: 'Green beans',
        pantryDays: null,
    },
    { category: 'Vegetable', freezerDays: 365, fridgeDays: 5, name: 'Peas', pantryDays: null },
    { category: 'Vegetable', freezerDays: 365, fridgeDays: 30, name: 'Cabbage', pantryDays: 7 },
    {
        category: 'Vegetable',
        freezerDays: 120,
        fridgeDays: 10,
        name: 'Herbs (fresh)',
        pantryDays: 2,
    },
    { category: 'Dairy', freezerDays: 365, fridgeDays: 90, name: 'Butter', pantryDays: 2 },
    { category: 'Dairy', freezerDays: 365, fridgeDays: 90, name: 'Margarine', pantryDays: null },
    {
        category: 'Dairy',
        freezerDays: 90,
        fridgeDays: 7,
        name: 'Milk (whole or low-fat)',
        pantryDays: null,
    },
    {
        category: 'Dairy',
        freezerDays: 90,
        fridgeDays: 7,
        name: 'Cream (heavy or light)',
        pantryDays: null,
    },
    { category: 'Dairy', freezerDays: 90, fridgeDays: 7, name: 'Half and half', pantryDays: null },
    { category: 'Dairy', freezerDays: 60, fridgeDays: 14, name: 'Yogurt', pantryDays: null },
    { category: 'Dairy', freezerDays: null, fridgeDays: 14, name: 'Sour cream', pantryDays: null },
    { category: 'Dairy', freezerDays: 60, fridgeDays: 14, name: 'Cream cheese', pantryDays: null },
    { category: 'Dairy', freezerDays: 60, fridgeDays: 7, name: 'Cottage cheese', pantryDays: null },
    {
        category: 'Dairy',
        freezerDays: 180,
        fridgeDays: 42,
        name: 'Cheese (hard, e.g. cheddar, Swiss)',
        pantryDays: null,
    },
    {
        category: 'Dairy',
        freezerDays: 60,
        fridgeDays: 7,
        name: 'Cheese (soft, e.g. Brie, goat cheese)',
        pantryDays: null,
    },
    {
        category: 'Dairy',
        freezerDays: 90,
        fridgeDays: 30,
        name: 'Cheese (shredded or sliced, packaged)',
        pantryDays: null,
    },
    {
        category: 'Dairy',
        freezerDays: null,
        fridgeDays: 730,
        name: 'Parmesan (grated, shelf-stable canister)',
        pantryDays: 365,
    },
    { category: 'Dairy', freezerDays: 60, fridgeDays: null, name: 'Ice cream', pantryDays: null },
    {
        category: 'Dairy',
        freezerDays: null,
        fridgeDays: 21,
        name: 'Whipped cream (aerosol can)',
        pantryDays: null,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Ketchup',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Mustard',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 180,
        name: 'Mayonnaise (unopened)',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 60,
        name: 'Mayonnaise (opened)',
        pantryDays: null,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 240,
        name: 'BBQ sauce',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 1825,
        name: 'Soy sauce',
        pantryDays: 1095,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 1095,
        name: 'Hot sauce',
        pantryDays: 730,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Salad dressing (bottled, unopened)',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 90,
        name: 'Salad dressing (opened)',
        pantryDays: null,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: null,
        name: 'Vinegar (white, apple cider, etc.)',
        pantryDays: 1825,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 730,
        name: 'Pickles (unopened jar)',
        pantryDays: 365,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 90,
        name: 'Pickles (opened jar)',
        pantryDays: null,
    },
    { category: 'Condiments', freezerDays: null, fridgeDays: 365, name: 'Relish', pantryDays: 365 },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Jam or jelly (unopened)',
        pantryDays: 365,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 180,
        name: 'Jam or jelly (opened)',
        pantryDays: null,
    },
    {
        category: 'Condiments',
        freezerDays: null,
        fridgeDays: 365,
        name: 'Peanut sauce or tahini',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: 180,
        fridgeDays: 30,
        name: 'Pesto (jarred)',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: 180,
        fridgeDays: 365,
        name: 'Salsa (unopened)',
        pantryDays: 180,
    },
    {
        category: 'Condiments',
        freezerDays: 90,
        fridgeDays: 14,
        name: 'Salsa (opened)',
        pantryDays: null,
    },
];
