export const FoodExpirationData: any[] = [
  { "name": "Egg, chicken, ham, tuna, and macaroni salads", "category": "Salad", "fridgeDays": 4, "freezerDays": null },
  { "name": "Hot dogs (opened)", "category": "Hot dogs", "fridgeDays": 7, "freezerDays": 45 },
  { "name": "Hot dogs (unopened)", "category": "Hot dogs", "fridgeDays": 14, "freezerDays": 45 },
  { "name": "Luncheon meat (opened or deli sliced)", "category": "Luncheon meat", "fridgeDays": 5, "freezerDays": 45 },
  { "name": "Luncheon meat (unopened)", "category": "Luncheon meat", "fridgeDays": 14, "freezerDays": 45 },
  { "name": "Bacon", "category": "Bacon and sausage", "fridgeDays": 7, "freezerDays": 30 },
  { "name": "Sausage (raw)", "category": "Bacon and sausage", "fridgeDays": 2, "freezerDays": 45 },
  { "name": "Sausage (fully cooked)", "category": "Bacon and sausage", "fridgeDays": 7, "freezerDays": 45 },
  { "name": "Ground meats (beef, poultry, etc.)", "category": "Ground meats", "fridgeDays": 2, "freezerDays": 105 },
  { "name": "Steaks", "category": "Fresh meat", "fridgeDays": 5, "freezerDays": 270 },
  { "name": "Chops", "category": "Fresh meat", "fridgeDays": 5, "freezerDays": 270 },
  { "name": "Roasts", "category": "Fresh meat", "fridgeDays": 5, "freezerDays": 270 },
  { "name": "Ham (fresh, uncured, uncooked)", "category": "Ham", "fridgeDays": 5, "freezerDays": 180 },
  { "name": "Ham (fresh, uncured, cooked)", "category": "Ham", "fridgeDays": 4, "freezerDays": 105 },
  { "name": "Ham (cured, cook-before-eating, uncooked)", "category": "Ham", "fridgeDays": 7, "freezerDays": 105 },
  { "name": "Ham (fully-cooked, vacuum-sealed, unopened)", "category": "Ham", "fridgeDays": 14, "freezerDays": 45 },
  { "name": "Ham (cooked, store-wrapped, slices or spiral)", "category": "Ham", "fridgeDays": 5, "freezerDays": 45 },
  { "name": "Ham (country, cooked)", "category": "Ham", "fridgeDays": 7, "freezerDays": 30 },
  { "name": "Ham (canned, keep refrigerated)", "category": "Ham", "fridgeDays": 225, "freezerDays": null },
  { "name": "Ham (canned, shelf-stable, opened)", "category": "Ham", "fridgeDays": 4, "freezerDays": 45 },
  { "name": "Prosciutto or Serrano ham (cut)", "category": "Ham", "fridgeDays": 75, "freezerDays": 30 },
  { "name": "Chicken or turkey (whole)", "category": "Poultry", "fridgeDays": 2, "freezerDays": 365 },
  { "name": "Chicken or turkey (pieces)", "category": "Poultry", "fridgeDays": 2, "freezerDays": 270 },
  { "name": "Fatty fish (salmon, mackerel, tuna, etc.)", "category": "Fish", "fridgeDays": 2, "freezerDays": 75 },
  { "name": "Lean fish (cod, haddock, etc.)", "category": "Fish", "fridgeDays": 2, "freezerDays": 180 },
  { "name": "Fresh crab meat", "category": "Shellfish", "fridgeDays": 3, "freezerDays": 90 },
  { "name": "Fresh lobster", "category": "Shellfish", "fridgeDays": 3, "freezerDays": 90 },
  { "name": "Live crab/lobster", "category": "Shellfish", "fridgeDays": 1, "freezerDays": null },
  { "name": "Live clams, mussels, oysters, scallops", "category": "Shellfish", "fridgeDays": 7, "freezerDays": null },
  { "name": "Shrimp or crayfish", "category": "Shellfish", "fridgeDays": 4, "freezerDays": 360 },
  { "name": "Shucked clams/mussels/oysters/scallops", "category": "Shellfish", "fridgeDays": 7, "freezerDays": 105 },
  { "name": "Squid", "category": "Shellfish", "fridgeDays": 2, "freezerDays": 360 },
  { "name": "Raw eggs in shell", "category": "Eggs", "fridgeDays": 28, "freezerDays": null },
  { "name": "Raw egg whites or yolks", "category": "Eggs", "fridgeDays": 3, "freezerDays": 365 },
  { "name": "Hard-cooked eggs", "category": "Eggs", "fridgeDays": 7, "freezerDays": null },
  { "name": "Egg substitutes (liquid, unopened)", "category": "Eggs", "fridgeDays": 7, "freezerDays": null },
  { "name": "Egg substitutes (liquid, opened)", "category": "Eggs", "fridgeDays": 3, "freezerDays": null },
  { "name": "Egg substitutes (frozen, unopened)", "category": "Eggs", "fridgeDays": 7, "freezerDays": 365 },
  { "name": "Egg substitutes (frozen, opened)", "category": "Eggs", "fridgeDays": 4, "freezerDays": null },
  { "name": "Casseroles with eggs", "category": "Casseroles", "fridgeDays": 4, "freezerDays": 75 },
  { "name": "Eggnog (commercial)", "category": "Eggnog", "fridgeDays": 4, "freezerDays": 180 },
  { "name": "Eggnog (homemade)", "category": "Eggnog", "fridgeDays": 3, "freezerDays": null },
  { "name": "Pie (pumpkin or pecan)", "category": "Pies", "fridgeDays": 4, "freezerDays": 45 },
  { "name": "Pie (custard or chiffon)", "category": "Pies", "fridgeDays": 4, "freezerDays": null },
  { "name": "Quiche with filling", "category": "Quiche", "fridgeDays": 5, "freezerDays": 75 },
  { "name": "Soups and stews", "category": "Soups", "fridgeDays": 4, "freezerDays": 75 },
  { "name": "Cooked meat or poultry leftovers", "category": "Leftovers", "fridgeDays": 4, "freezerDays": 120 },
  { "name": "Chicken nuggets or patties", "category": "Leftovers", "fridgeDays": 4, "freezerDays": 60 },
  { "name": "Pizza", "category": "Leftovers", "fridgeDays": 4, "freezerDays": 45 },
  { "name": "Flour (all-purpose)", "category": "Dry goods", "pantryDays": 180, "fridgeDays": 365, "freezerDays": 730 },
  { "name": "Sugar (white, granulated)", "category": "Dry goods", "pantryDays": 1825, "fridgeDays": null, "freezerDays": null },
  { "name": "Brown sugar", "category": "Dry goods", "pantryDays": 720, "fridgeDays": null, "freezerDays": null },
  { "name": "Powdered sugar", "category": "Dry goods", "pantryDays": 720, "fridgeDays": null, "freezerDays": null },
  { "name": "Rice (white, uncooked)", "category": "Dry goods", "pantryDays": 1825, "fridgeDays": null, "freezerDays": null },
  { "name": "Rice (brown, uncooked)", "category": "Dry goods", "pantryDays": 180, "fridgeDays": 365, "freezerDays": 730 },
  { "name": "Pasta (dry, uncooked)", "category": "Dry goods", "pantryDays": 720, "fridgeDays": null, "freezerDays": null },
  { "name": "Oats", "category": "Dry goods", "pantryDays": 365, "fridgeDays": 730, "freezerDays": 730 },
  { "name": "Cereal (unopened)", "category": "Dry goods", "pantryDays": 365, "fridgeDays": null, "freezerDays": null },
  { "name": "Cereal (opened)", "category": "Dry goods", "pantryDays": 60, "fridgeDays": null, "freezerDays": null },
  { "name": "Beans (dried, uncooked)", "category": "Dry goods", "pantryDays": 730, "fridgeDays": null, "freezerDays": null },
  { "name": "Lentils", "category": "Dry goods", "pantryDays": 730, "fridgeDays": null, "freezerDays": null },
  { "name": "Bread (store-bought, sliced)", "category": "Bakery", "pantryDays": 7, "fridgeDays": 14, "freezerDays": 90 },
  { "name": "Bread (homemade)", "category": "Bakery", "pantryDays": 3, "fridgeDays": 7, "freezerDays": 90 },
  { "name": "Coffee beans (whole)", "category": "Dry goods", "pantryDays": 180, "fridgeDays": 180, "freezerDays": 730 },
  { "name": "Coffee (ground)", "category": "Dry goods", "pantryDays": 90, "fridgeDays": 180, "freezerDays": 730 },
  { "name": "Tea (loose or bagged)", "category": "Dry goods", "pantryDays": 730, "fridgeDays": null, "freezerDays": null },
  { "name": "Peanut butter", "category": "Pantry staples", "pantryDays": 180, "fridgeDays": 365, "freezerDays": null },
  { "name": "Cooking oil (vegetable, canola)", "category": "Pantry staples", "pantryDays": 365, "fridgeDays": null, "freezerDays": null },
  { "name": "Olive oil", "category": "Pantry staples", "pantryDays": 730, "fridgeDays": null, "freezerDays": null },
  { "name": "Honey", "category": "Pantry staples", "pantryDays": 1825, "fridgeDays": null, "freezerDays": null },
  { "name": "Salt", "category": "Dry goods", "pantryDays": 3650, "fridgeDays": null, "freezerDays": null },
  { "name": "Pepper (ground)", "category": "Dry goods", "pantryDays": 1095, "fridgeDays": null, "freezerDays": null },
  { "name": "Spices and herbs (dried)", "category": "Dry goods", "pantryDays": 730, "fridgeDays": null, "freezerDays": null },

  { "name": "Apples", "category": "Fruit", "pantryDays": 14, "fridgeDays": 60, "freezerDays": 365 },
  { "name": "Bananas", "category": "Fruit", "pantryDays": 7, "fridgeDays": 10, "freezerDays": 90 },
  { "name": "Oranges", "category": "Fruit", "pantryDays": 14, "fridgeDays": 30, "freezerDays": 90 },
  { "name": "Lemons", "category": "Fruit", "pantryDays": 14, "fridgeDays": 30, "freezerDays": 120 },
  { "name": "Limes", "category": "Fruit", "pantryDays": 14, "fridgeDays": 30, "freezerDays": 120 },
  { "name": "Grapes", "category": "Fruit", "pantryDays": 2, "fridgeDays": 14, "freezerDays": 365 },
  { "name": "Berries (strawberries, raspberries, etc.)", "category": "Fruit", "pantryDays": 1, "fridgeDays": 7, "freezerDays": 365 },
  { "name": "Melons (whole)", "category": "Fruit", "pantryDays": 7, "fridgeDays": 10, "freezerDays": 60 },
  { "name": "Melons (cut)", "category": "Fruit", "pantryDays": null, "fridgeDays": 5, "freezerDays": 60 },
  { "name": "Avocados", "category": "Fruit", "pantryDays": 7, "fridgeDays": 10, "freezerDays": 60 },
  { "name": "Tomatoes", "category": "Vegetable", "pantryDays": 7, "fridgeDays": 14, "freezerDays": 120 },
  { "name": "Potatoes (white, russet)", "category": "Vegetable", "pantryDays": 60, "fridgeDays": null, "freezerDays": null },
  { "name": "Sweet potatoes", "category": "Vegetable", "pantryDays": 60, "fridgeDays": null, "freezerDays": null },
  { "name": "Onions (whole)", "category": "Vegetable", "pantryDays": 30, "fridgeDays": 90, "freezerDays": 365 },
  { "name": "Garlic (whole heads)", "category": "Vegetable", "pantryDays": 90, "fridgeDays": 120, "freezerDays": 365 },
  { "name": "Carrots", "category": "Vegetable", "pantryDays": 7, "fridgeDays": 30, "freezerDays": 365 },
  { "name": "Celery", "category": "Vegetable", "pantryDays": null, "fridgeDays": 21, "freezerDays": 120 },
  { "name": "Bell peppers", "category": "Vegetable", "pantryDays": 3, "fridgeDays": 14, "freezerDays": 120 },
  { "name": "Lettuce", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": null },
  { "name": "Spinach", "category": "Vegetable", "pantryDays": null, "fridgeDays": 5, "freezerDays": 365 },
  { "name": "Broccoli", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": 365 },
  { "name": "Cauliflower", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": 365 },
  { "name": "Zucchini", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": 90 },
  { "name": "Cucumbers", "category": "Vegetable", "pantryDays": 5, "fridgeDays": 10, "freezerDays": null },
  { "name": "Mushrooms", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": 120 },
  { "name": "Corn (fresh, in husk)", "category": "Vegetable", "pantryDays": 1, "fridgeDays": 3, "freezerDays": 365 },
  { "name": "Green beans", "category": "Vegetable", "pantryDays": null, "fridgeDays": 7, "freezerDays": 365 },
  { "name": "Peas", "category": "Vegetable", "pantryDays": null, "fridgeDays": 5, "freezerDays": 365 },
  { "name": "Cabbage", "category": "Vegetable", "pantryDays": 7, "fridgeDays": 30, "freezerDays": 365 },
  { "name": "Herbs (fresh)", "category": "Vegetable", "pantryDays": 2, "fridgeDays": 10, "freezerDays": 120 },
  { "name": "Butter", "category": "Dairy", "pantryDays": 2, "fridgeDays": 90, "freezerDays": 365 },
  { "name": "Margarine", "category": "Dairy", "pantryDays": null, "fridgeDays": 90, "freezerDays": 365 },
  { "name": "Milk (whole or low-fat)", "category": "Dairy", "pantryDays": null, "fridgeDays": 7, "freezerDays": 90 },
  { "name": "Cream (heavy or light)", "category": "Dairy", "pantryDays": null, "fridgeDays": 7, "freezerDays": 90 },
  { "name": "Half and half", "category": "Dairy", "pantryDays": null, "fridgeDays": 7, "freezerDays": 90 },
  { "name": "Yogurt", "category": "Dairy", "pantryDays": null, "fridgeDays": 14, "freezerDays": 60 },
  { "name": "Sour cream", "category": "Dairy", "pantryDays": null, "fridgeDays": 14, "freezerDays": null },
  { "name": "Cream cheese", "category": "Dairy", "pantryDays": null, "fridgeDays": 14, "freezerDays": 60 },
  { "name": "Cottage cheese", "category": "Dairy", "pantryDays": null, "fridgeDays": 7, "freezerDays": 60 },
  { "name": "Cheese (hard, e.g. cheddar, Swiss)", "category": "Dairy", "pantryDays": null, "fridgeDays": 42, "freezerDays": 180 },
  { "name": "Cheese (soft, e.g. Brie, goat cheese)", "category": "Dairy", "pantryDays": null, "fridgeDays": 7, "freezerDays": 60 },
  { "name": "Cheese (shredded or sliced, packaged)", "category": "Dairy", "pantryDays": null, "fridgeDays": 30, "freezerDays": 90 },
  { "name": "Parmesan (grated, shelf-stable canister)", "category": "Dairy", "pantryDays": 365, "fridgeDays": 730, "freezerDays": null },
  { "name": "Ice cream", "category": "Dairy", "pantryDays": null, "fridgeDays": null, "freezerDays": 60 },
  { "name": "Whipped cream (aerosol can)", "category": "Dairy", "pantryDays": null, "fridgeDays": 21, "freezerDays": null },
  { "name": "Ketchup", "category": "Condiments", "pantryDays": 180, "fridgeDays": 365, "freezerDays": null },
  { "name": "Mustard", "category": "Condiments", "pantryDays": 180, "fridgeDays": 365, "freezerDays": null },
  { "name": "Mayonnaise (unopened)", "category": "Condiments", "pantryDays": 180, "fridgeDays": 180, "freezerDays": null },
  { "name": "Mayonnaise (opened)", "category": "Condiments", "pantryDays": null, "fridgeDays": 60, "freezerDays": null },
  { "name": "BBQ sauce", "category": "Condiments", "pantryDays": 180, "fridgeDays": 240, "freezerDays": null },
  { "name": "Soy sauce", "category": "Condiments", "pantryDays": 1095, "fridgeDays": 1825, "freezerDays": null },
  { "name": "Hot sauce", "category": "Condiments", "pantryDays": 730, "fridgeDays": 1095, "freezerDays": null },
  { "name": "Salad dressing (bottled, unopened)", "category": "Condiments", "pantryDays": 180, "fridgeDays": 365, "freezerDays": null },
  { "name": "Salad dressing (opened)", "category": "Condiments", "pantryDays": null, "fridgeDays": 90, "freezerDays": null },
  { "name": "Vinegar (white, apple cider, etc.)", "category": "Condiments", "pantryDays": 1825, "fridgeDays": null, "freezerDays": null },
  { "name": "Pickles (unopened jar)", "category": "Condiments", "pantryDays": 365, "fridgeDays": 730, "freezerDays": null },
  { "name": "Pickles (opened jar)", "category": "Condiments", "pantryDays": null, "fridgeDays": 90, "freezerDays": null },
  { "name": "Relish", "category": "Condiments", "pantryDays": 365, "fridgeDays": 365, "freezerDays": null },
  { "name": "Jam or jelly (unopened)", "category": "Condiments", "pantryDays": 365, "fridgeDays": 365, "freezerDays": null },
  { "name": "Jam or jelly (opened)", "category": "Condiments", "pantryDays": null, "fridgeDays": 180, "freezerDays": null },
  { "name": "Peanut sauce or tahini", "category": "Condiments", "pantryDays": 180, "fridgeDays": 365, "freezerDays": null },
  { "name": "Pesto (jarred)", "category": "Condiments", "pantryDays": 180, "fridgeDays": 30, "freezerDays": 180 },
  { "name": "Salsa (unopened)", "category": "Condiments", "pantryDays": 180, "fridgeDays": 365, "freezerDays": 180 },
  { "name": "Salsa (opened)", "category": "Condiments", "pantryDays": null, "fridgeDays": 14, "freezerDays": 90 }
]
