"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var user_1 = require("./routes/user");
var recipe_1 = require("./routes/recipe");
var pantry_1 = require("./routes/pantry");
var meta_1 = require("./routes/meta");
var events_1 = require("./routes/events");
var household_1 = require("./routes/household");
var express_2 = require("@clerk/express");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use((0, express_2.clerkMiddleware)({ debug: true }));
app.use('/meta', meta_1.default);
app.use('/user', user_1.default);
app.use('/', recipe_1.default);
app.use('/', pantry_1.default);
app.use('/', household_1.default);
app.use('/events', events_1.default);
exports.default = app;
